# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            #access_denied_handler: AppBundle\Security\AccessDeniedHandler
            form_login:
                login_path: /login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: true
                default_target_path: dashboard




            logout: true
            anonymous: true


    access_control:

        - { path: '^/gestion-back', roles: [ROLE_USER,ROLE_ADMIN] }
