<?php

namespace HotelBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function get_res_client(){
        $em =$this->getEntityManager();

        $query = $em->createQuery(' select cl.id, cl.nom , cl.prenom, cl.email, cl.telephone, res.id from HotelBundle:Client cl 
                  join HotelBundle:Reservation res  on (res.client = cl.id) 
                         
        ');

        return $query;

    }

    public function affecter_client_reservation($client, $id_res){
        $em =$this->getEntityManager();

        $query = $em->createQuery(' update HotelBundle:Reservation r set r.client = :client where r.id = :id
        ')->setParameters(array(
            'client'=> $client,
            'id'=>$id_res))->getResult();

        return $query;

    }

}
