<?php

namespace HotelBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function get_res_archive(){
        $em =$this->getEntityManager();

        $query = $em->createQuery(' select res.id, res.dateArrive, res.dateSortie, res.dateCreation, res.typeChambre, res.treated
  res.client from HotelBundle:Reservation res where res.archive is true;
                         
        ');

        return $query;

    }


    public function get_res(){
        $em =$this->getEntityManager();

        $query = $em->createQuery(' select res.id, res.dateArrive, res.dateSortie, res.dateCreation, res.typeChambre, res.treated
  res.client from HotelBundle:Reservation res where res.archive is false;
                         
        ');

        return $query;

    }
}
